version: '3'

services:

  app:
    build:
      context: /jenkins-test/ci_cd
      dockerfile: /jenkins-test/ci_cd/Dockerfile
    image: hello-spring-image
    ports:
      - "80:3000"
    environment:
      - ROOT_URL=http://localhost

